version: '2'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloudpasswd
      - MYSQL_PASSWORD=nextcloudpasswd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    container_name: app-server
    image: nextcloud:fpm
    stdin_open: true
    tty: true
    ports:
      - '80'
      - '9000'
    links:
      - db
    volumes:
      - ./nextcloud:/var/www/html
      - /mnt/external_disk:/mnt/external_disk
      - ./entrypoint.sh:/entrypoint.sh
    restart: always

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    expose:
      - '80'
      - '443'
    volumes:
      - ./document_data:/var/www/onlyoffice/Data
      - ./document_log:/var/log/onlyoffice
  nginx:
    container_name: nginx-server
    image: nginx
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 127.0.0.1:8001:80
        #- 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nextcloud:/var/www/html

